version: 2.1

jobs:
  build:  
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          working_directory: ./
          name: Restore
          command: dotnet restore
      - run:
          working_directory: ./
          name: Build
          command: dotnet build
      - run:
          working_directory: ./
          name: Test
          command: dotnet test
workflows:
  sample: 
    jobs:
      - build

