# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:  
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          working_directory: ~/
          name: restore
          command: dotnet restore
      - run:
          working_directory: ~/
          name: build
          command: dotnet build

  tests:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: dotnet test

workflows:
  sample: 
    jobs:
      - build
      - tests
